apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: k8s-garsonical-com
spec:
  secretName: k8s-garsonical-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.garsonical.com
  dnsNames:
    - k8s.garsonical.com
