apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: garsonical-com-tls
spec:
  secretName: garsonical-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: garsonical.com
  dnsNames:
    - garsonical.com
    - www.garsonical.com
